services:
  nginx-proxy:
    build: nginx
    volumes:
      - ./nginx/default.conf:/tmp/default.conf
    environment:
      - FLASK_SERVER_ADDR=mixtapestudy:8000
    ports:
      - "80:80"
    depends_on:
      - mixtapestudy
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:80/health-check || exit 1"]
      interval: 2s
      timeout: 10s
      retries: 3
  # TODO: Add Postgres
  mixtapestudy:
    build: .
    ports:
      - '8000:8000'
    environment:
      OAUTH_REDIRECT_BASE_URL: 'http://127.0.0.1'
      # Set these in a .env file
      SPOTIFY_CLIENT_SECRET: "${SPOTIFY_CLIENT_SECRET}"
      DATABASE_URL: "${DATABASE_URL}"
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:8000/flask-health-check || exit 1"]
      interval: 2s
      timeout: 10s
      retries: 3
